server:
  port: 8080

spring:
  application:
    name: market-data-service
  
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/stock-analytics}
      database: stock-analytics
  
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: stockTick:com.stockanalytics.shared.model.StockTick
    consumer:
      group-id: market-data-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: stockTick:com.stockanalytics.shared.model.StockTick

# Kafka Topics
kafka:
  topic:
    stocks:
      ticks: stocks.ticks

# Tick Generator Configuration
tick:
  generator:
    default:
      symbols: INFY,TCS,RELIANCE,HDFC,ICICIBANK
      rate: 50

# Logging
logging:
  level:
    com.stockanalytics.marketdata: INFO
    org.springframework.kafka: INFO
    org.springframework.data.mongodb: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Profiles
---
spring:
  config:
    activate:
      on-profile: docker
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS_DOCKER:redpanda:9092}
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://host.docker.internal:27017/stock-analytics}
