global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Stock Analytics Platform Services
  - job_name: 'market-data'
    static_configs:
      - targets: ['localhost:8081']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s

  - job_name: 'analytics'
    static_configs:
      - targets: ['localhost:8082']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s

  - job_name: 'portfolio'
    static_configs:
      - targets: ['localhost:8083']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s

  - job_name: 'alerts'
    static_configs:
      - targets: ['localhost:8084']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s

  # Infrastructure Services
  - job_name: 'redpanda'
    static_configs:
      - targets: ['localhost:9092']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['localhost:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'mongodb'
    static_configs:
      - targets: ['localhost:27017']
    metrics_path: '/metrics'
    scrape_interval: 30s
